image: maven:3-jdk-8
build:
  stage: build
  script:
    - mvn clean test
    #- mvn sonar:sonar  -Dsonar.projectKey=coverage  -Dsonar.host.url=http://34.219.94.74:9000  -Dsonar.login=80be7644a57f67cc85794fc092b9d76409fd8987
    - cat target/site/jacoco/index.html | grep -o '.*'
  allow_failure: false
  coverage: "/Total.*?([0-9]{1,3})%/"
  artifacts:
    paths:
      - target/site/jacoco/index.html
      - target/surefire-reports/TEST-*.xml
    reports:
      junit:
        - target/site/jacoco/index.html
        - target/surefire-reports/TEST-*.xml
  only:
      changes:
        - README.md
        - pom.xml
        - src/*    