name: java ci

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test with junit
        run: mvn test
