name: Java CI

on: [push]

jobs:
    ping:
        name: ping
        runs-on: self hosted
        steps:
            -   uses: actions/checkout@v2
            -   shell: bash
            -   run: chmod u+x ping.sh && ./ping.sh > output.txt
            -   run: cat output.txt   
  
     
        
        
