name: Java CI

on: [push]

jobs:
  ping:
    name: ping
      runs-on: self hosted
        steps:
          - name: Run build script
            uses: actions/checkout@v2
            run: chmod u+x ping.sh && ./ping.sh > output.txt && cat output.txt 
            shell: bash
     
        
        
