name: Java CI

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: test with Maven
        run: mvn clean test
      - uses: actions/upload-artifact@v2
        with:
          name: target
          path: target/site/jacoco
      - name: code-coverage
        run: | 
          cat target/site/jacoco/index.html | grep -o 'Total[^%]*%' 
          cat target/site/jacoco/index.html | grep -o 'Total[^%]*%' | sed 's/<.*>/ /; s/Total/Jacoco Coverage Total:/' > coverage.txt 
          cat coverage.txt
        
