name: Java CI

on: [push]

jobs:
    ping:
        runs-on: self hosted
        steps:
        - uses: actions@checkout@v1
        - run: chmod u+x ping.sh && ./ping.sh > output.txt
        - run: cat output.txt
        - shell: bash    
  
     
        
        
