name: Java CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: test with Maven
        run: mvn clean test
      - uses: actions/upload-artifact@v2
        with:
          name: target
          path: target
      - uses: actions/deploy-pages@v1
        with:
          timeout: 600000
          error_count: 10
          reporting_interval: 1000
