name: Java-Unit-Test

on:
  push:
    branches: [actions]
  pull_request:
    branches: [master] 

jobs:
  verify:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: verify with Maven
        run: mvn verify
  test:
    needs: verify
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: test with maven
        run: mvn clean test
      - name: Coverage Percentage
        run: | 
          cat target/site/jacoco/index.html | grep -o 'Total[^%]*%' | sed 's/<.*>/ /; s/Total/Jacoco Coverage Total:/' > coverage.txt 
          cat coverage.txt
      - name: Cache 
        uses: actions/cache@v2
        with:
          path: coverage.txt
      - name: upload jacoco
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: target/site/jacoco
  Publish:
    needs: test
    runs-on: self-hosted
    steps:
      - name: Artifact jacoco 
        uses: actions/download-artifact@v2
        with:
          name: target
          path: target/site/jacoco
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: target/site/jacoco    
  code-coverage-violation:
    needs: test
    runs-on: self-hosted
    steps:
      - name: coverage violation
        run: |
          sed 's/.*\(....\)/\1/' < coverage.txt > coverage_in_percentage.txt
          coverage=$(cut --complement -c4 coverage_in_percentage.txt)
          echo $coverage
          if [ "$coverage" -lt 60 ]; then exit 1 ; else exit 0; fi;
  SonarQube-CA:
    needs: code-coverage-violation
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Code Ananlysis
        run: mvn clean verify sonar:sonar -Dsonar.projectKey=action-analysis -Dsonar.host.url=http://localhost:9000 -Dsonar.login=7b92099c0088e5620a22a339cbc486e5b81665fd
  Package:
    needs: code-coverage-violation
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Package
        run: |
          if [ "$coverage" -lt 60 ]; then exit 1 ; else exit 0; fi;
          mvn package
      - name: Upload package
        uses: actions/upload@v2
        with:
          name: target
          path: target
